Catalog/Catalog/Controllers/MonthController.cs
using System.Collections.Generic;
using System.Linq;
using Catalog.Infrastructure.Repositories;
using System.Web.Mvc;
using Catalog.Models;

namespace Catalog.Controllers
{
    public class MonthController : Controller
    {
        // GET: Month
        public ActionResult Index()
        {
            return View();
        }

        public JsonResult GetMonths()
        {
            using (var monthRep = new MonthRepository())
            {
                var months = monthRep.Get();

                var monthsViewModel = months.Select(month => new MonthViewModel()
                {
                    Id = month.Id,
                    MonthName = month.MonthName,
                    Value = month.Value
                }).ToList();

                return Json(monthsViewModel, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public JsonResult UpdateMonths(MonthViewModel[] monthViewModel)
        {
            using (var monthRep = new MonthRepository())
            {
                if (monthViewModel == null) return null;

                foreach (var item in monthViewModel)
                {
                    var month = monthRep.GetByName(item.MonthName);

                    if (month.Value == item.Value) continue;
                    month.Value = item.Value;
                    monthRep.Edit(month);
                }
            }

            return Json(monthViewModel, JsonRequestBehavior.AllowGet);
        }
    }
}

Catalog/Catalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <link href="~/Content/Wait.css" rel="stylesheet"/>
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Catalog", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Months", "Index", "Month")</li>
                    <li>@Html.ActionLink("Wait", "Index", "Wait")</li>
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Product", "Index", "Product")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/Chart.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>